# Generated by Django 2.0.1 on 2018-01-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('parents_string', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='viewer.Taxon')),
            ],
        ),
    ]
