# Generated by Django 2.0.1 on 2018-01-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
