# Generated by Django 2.0.1 on 2018-02-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20180208_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='parents_string',
        ),
    ]
