# Generated by Django 2.0.1 on 2018-01-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_taxon_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='wikidata_id',
            field=models.CharField(db_index=True, default='', max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
