# Generated by Django 2.0.1 on 2019-10-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_taxon_parents_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
