# Generated by Django 2.0.1 on 2018-01-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_taxon_wikidata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
