# Generated by Django 3.0.6 on 2020-05-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_taxon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='wikipedia_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
