# Generated by Django 2.0.1 on 2018-01-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20180109_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='wikidata_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
