# Generated by Django 3.0.6 on 2020-05-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_taxon_wikipedia_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='alias',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
