# Generated by Django 3.0.6 on 2020-05-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_taxon_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='image',
            field=models.URLField(default=None, max_length=1024, null=True),
        ),
    ]
