# Generated by Django 3.0.6 on 2020-06-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20200531_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='wikipedia_title',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
